name: amnre
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - pip=21.0.1
  - python=3.8.5
  - pip:
    - h5py==3.2.1
    - matplotlib==3.4.1
    - numpy==1.19.5
    - pandas==1.2.3
    - scikit-learn==0.24.2
    - seaborn==0.11.1
    - torch==1.8.1
    - torchist==0.1.6
    - tqdm==4.59.0
